server:
  port: 8888
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/edgarSucre/configuration-repository
          uri: https://github.com/edgarSucre/configuration-server