server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edgarSucre/configuration-repository
        #native:
          #searchLocations: file:///Users/edgar/Documents/own/spring/configuration-server/src/main/resources/config